apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-blue
      deployment: blue
  template:
    metadata:
      labels:
        app: django-blue
        deployment: blue
    spec:
      containers:
        - name: web
          image: registry.gitlab.com/haritz.saiz/popbl2:latest
          imagePullPolicy: Always          
          ports:
            - containerPort: 8000  

        # - name: nginx
        #   image: nginx:stable          
        #   imagePullPolicy: Always
        #   ports:
        #     - containerPort: 8000
        #   volumeMounts:
        #     - name: nginx-config-volume
        #       subPath: local.conf
        #       mountPath: /etc/nginx/conf.d/local.conf
      imagePullSecrets:
        - name: regcred