# pull official base image
FROM registry.gitlab.com/haritz.saiz/popbl2:base

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set working directory
RUN mkdir /code
WORKDIR /code

# install requirements
COPY web/requirements.txt /code/
RUN pip install --upgrade pip && pip install -r requirements.txt

# copy code
COPY web/app/ /code/
CMD [ "python",  "./manage.py", "runserver", "0.0.0.0:8000" ]