apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prod-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: prod-secret
  rules:
  - host: prod.itapp.eus
    http:
      paths:
      - backend:
          serviceName: django
          servicePort: 80