apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  ports:
    - name: django-port
      protocol: TCP
      port: 80
      targetPort: 8000      
  selector:
    app: django-blue
    deployment: blue