apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/xetxezarreta/Documentos/POPBL2/web/app"